services:
  python-video-streamer:
    restart: unless-stopped
    build:
      context: .
    devices:
     - /dev/video0:/dev/video0
    ports:
      - "8081:8081"
    environment:
      - TZ=America/New_York
      - PYTHONUNBUFFERED=True
